// Mocks generated by Mockito 5.2.0 from annotations
// in genderize/test/features/genderize/data/repositories/genderize_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:genderize/core/network/network_info.dart' as _i2;
import 'package:genderize/features/genderize/data/datasources/genderize_remote_data_source.dart'
    as _i4;
import 'package:genderize/features/genderize/data/models/genderize_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i2.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}

/// A class which mocks [GenderizeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenderizeRemoteDataSource extends _i1.Mock
    implements _i4.GenderizeRemoteDataSource {
  MockGenderizeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.GenderizeModel>? getPrediction(String? name) =>
      (super.noSuchMethod(Invocation.method(#getPrediction, [name]))
          as _i3.Future<_i5.GenderizeModel>?);
}

/// A class which mocks [GenderizeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenderizeRemoteDataSourceForTest extends _i1.Mock
    implements _i4.GenderizeRemoteDataSource {
  @override
  _i3.Future<_i5.GenderizeModel>? getPrediction(String? name) =>
      (super.noSuchMethod(Invocation.method(#getPrediction, [name]))
          as _i3.Future<_i5.GenderizeModel>?);
}
